server:
  port: 8083
spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/comment_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/