spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## User authentication service.
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        ## Article service
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/api/v1/articles/**

        # Public route for getting comments by article
        - id: comment-service-public
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/article/**

        # Private routes for other comment endpoints (requires authentication)
        - id: comment-service-private
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - name: AuthenticationFilter # Apply authentication to this route

server:
  port: 9191
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437