spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/api/v1/articles/**

server:
  port: 9191
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437