server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reaction_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
    cache:
      redis:
        time-to-live: 600000  # Thời gian tồn tại của cache (600 giây = 10 phút)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
